// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.neoshare

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object TransferApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Model returned by [FileHostApi.pickFiles] describing a natively-picked file.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PickedFileInfo (
  val path: String,
  val name: String,
  val sizeBytes: Long,
  val mimeType: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PickedFileInfo {
      val path = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val sizeBytes = pigeonVar_list[2] as Long
      val mimeType = pigeonVar_list[3] as String
      return PickedFileInfo(path, name, sizeBytes, mimeType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      name,
      sizeBytes,
      mimeType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PickedFileInfo
    return TransferApiPigeonUtils.deepEquals(this.path, other.path) && TransferApiPigeonUtils.deepEquals(this.name, other.name) && TransferApiPigeonUtils.deepEquals(this.sizeBytes, other.sizeBytes) && TransferApiPigeonUtils.deepEquals(this.mimeType, other.mimeType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TransferApiPigeonUtils.deepHash(this.path)
    result = 31 * result + TransferApiPigeonUtils.deepHash(this.name)
    result = 31 * result + TransferApiPigeonUtils.deepHash(this.sizeBytes)
    result = 31 * result + TransferApiPigeonUtils.deepHash(this.mimeType)
    return result
  }
}
private open class TransferApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PickedFileInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PickedFileInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FileHostApi {
  /**
   * Open the native file picker (supports multi-select).
   * Returns a list of [PickedFileInfo] objects for each selected file.
   */
  fun pickFiles(callback: (Result<List<PickedFileInfo>>) -> Unit)
  /**
   * Save a file from [tempPath] to the public Downloads folder via MediaStore
   * (Android) or the app's Documents directory (iOS).
   * Returns the final saved path / content URI.
   */
  fun saveToDownloads(tempPath: String, mimeType: String, fileName: String, callback: (Result<String>) -> Unit)
  /** Returns available storage space in bytes. */
  fun getFreeSpace(callback: (Result<Long>) -> Unit)

  companion object {
    /** The codec used by FileHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      TransferApiPigeonCodec()
    }
    /** Sets up an instance of `FileHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FileHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.neoshare.FileHostApi.pickFiles$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.pickFiles{ result: Result<List<PickedFileInfo>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransferApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TransferApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.neoshare.FileHostApi.saveToDownloads$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tempPathArg = args[0] as String
            val mimeTypeArg = args[1] as String
            val fileNameArg = args[2] as String
            api.saveToDownloads(tempPathArg, mimeTypeArg, fileNameArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransferApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TransferApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.neoshare.FileHostApi.getFreeSpace$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getFreeSpace{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransferApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TransferApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter → Android: control the TransferForegroundService.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface TransferServiceHostApi {
  /** Start the foreground service for the given transfer. */
  fun startUploadService(transferId: String)
  /** Stop the foreground service (upload finished or cancelled). */
  fun stopUploadService()
  /** Update the persistent notification progress (0–100). */
  fun updateProgress(percent: Long)

  companion object {
    /** The codec used by TransferServiceHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      TransferApiPigeonCodec()
    }
    /** Sets up an instance of `TransferServiceHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TransferServiceHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.neoshare.TransferServiceHostApi.startUploadService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val transferIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.startUploadService(transferIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              TransferApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.neoshare.TransferServiceHostApi.stopUploadService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopUploadService()
              listOf(null)
            } catch (exception: Throwable) {
              TransferApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.neoshare.TransferServiceHostApi.updateProgress$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val percentArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.updateProgress(percentArg)
              listOf(null)
            } catch (exception: Throwable) {
              TransferApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Android → Flutter: service lifecycle callbacks.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class TransferServiceFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by TransferServiceFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      TransferApiPigeonCodec()
    }
  }
  /** Called when the OS restarts the service after killing it under memory pressure. */
  fun onServiceRestarted(transferIdArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.neoshare.TransferServiceFlutterApi.onServiceRestarted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(transferIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(TransferApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
