// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsFileApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashFileApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsFileApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsFileApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsFileApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsFileApi(lhsKey, rhsKey) {
          if deepEqualsFileApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsFileApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashFileApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashFileApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashFileApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashFileApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashFileApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashFileApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Model returned by [FileHostApi.pickFiles] describing a natively-picked file.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PickedFileInfo: Hashable {
  var path: String
  var name: String
  var sizeBytes: Int64
  var mimeType: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PickedFileInfo? {
    let path = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let sizeBytes = pigeonVar_list[2] as! Int64
    let mimeType = pigeonVar_list[3] as! String

    return PickedFileInfo(
      path: path,
      name: name,
      sizeBytes: sizeBytes,
      mimeType: mimeType
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      name,
      sizeBytes,
      mimeType,
    ]
  }
  static func == (lhs: PickedFileInfo, rhs: PickedFileInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsFileApi(lhs.path, rhs.path) && deepEqualsFileApi(lhs.name, rhs.name) && deepEqualsFileApi(lhs.sizeBytes, rhs.sizeBytes) && deepEqualsFileApi(lhs.mimeType, rhs.mimeType)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PickedFileInfo")
    deepHashFileApi(value: path, hasher: &hasher)
    deepHashFileApi(value: name, hasher: &hasher)
    deepHashFileApi(value: sizeBytes, hasher: &hasher)
    deepHashFileApi(value: mimeType, hasher: &hasher)
  }
}

private class FileApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PickedFileInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FileApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PickedFileInfo {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FileApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FileApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FileApiPigeonCodecWriter(data: data)
  }
}

class FileApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FileApiPigeonCodec(readerWriter: FileApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FileHostApi {
  /// Open the native file picker (supports multi-select).
  /// Returns a list of [PickedFileInfo] objects for each selected file.
  func pickFiles(completion: @escaping (Result<[PickedFileInfo], Error>) -> Void)
  /// Save a file from [tempPath] to the public Downloads folder via MediaStore (Android)
  /// or the app's Documents directory (iOS). Returns the final saved path / content URI.
  func saveToDownloads(tempPath: String, mimeType: String, fileName: String, completion: @escaping (Result<String, Error>) -> Void)
  /// Returns available storage space in bytes.
  func getFreeSpace(completion: @escaping (Result<Int64, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FileHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FileApiPigeonCodec.shared }
  /// Sets up an instance of `FileHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FileHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Open the native file picker (supports multi-select).
    /// Returns a list of [PickedFileInfo] objects for each selected file.
    let pickFilesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neoshare.FileHostApi.pickFiles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickFilesChannel.setMessageHandler { _, reply in
        api.pickFiles { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickFilesChannel.setMessageHandler(nil)
    }
    /// Save a file from [tempPath] to the public Downloads folder via MediaStore (Android)
    /// or the app's Documents directory (iOS). Returns the final saved path / content URI.
    let saveToDownloadsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neoshare.FileHostApi.saveToDownloads\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveToDownloadsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tempPathArg = args[0] as! String
        let mimeTypeArg = args[1] as! String
        let fileNameArg = args[2] as! String
        api.saveToDownloads(tempPath: tempPathArg, mimeType: mimeTypeArg, fileName: fileNameArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveToDownloadsChannel.setMessageHandler(nil)
    }
    /// Returns available storage space in bytes.
    let getFreeSpaceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neoshare.FileHostApi.getFreeSpace\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFreeSpaceChannel.setMessageHandler { _, reply in
        api.getFreeSpace { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getFreeSpaceChannel.setMessageHandler(nil)
    }
  }
}
