// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsTransferApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashTransferApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsTransferApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsTransferApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsTransferApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsTransferApi(lhsKey, rhsKey) {
          if deepEqualsTransferApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsTransferApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashTransferApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashTransferApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashTransferApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashTransferApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashTransferApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashTransferApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Model returned by [FileHostApi.pickFiles] describing a natively-picked file.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PickedFileInfo: Hashable {
  var path: String
  var name: String
  var sizeBytes: Int64
  var mimeType: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PickedFileInfo? {
    let path = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let sizeBytes = pigeonVar_list[2] as! Int64
    let mimeType = pigeonVar_list[3] as! String

    return PickedFileInfo(
      path: path,
      name: name,
      sizeBytes: sizeBytes,
      mimeType: mimeType
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      name,
      sizeBytes,
      mimeType,
    ]
  }
  static func == (lhs: PickedFileInfo, rhs: PickedFileInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsTransferApi(lhs.path, rhs.path) && deepEqualsTransferApi(lhs.name, rhs.name) && deepEqualsTransferApi(lhs.sizeBytes, rhs.sizeBytes) && deepEqualsTransferApi(lhs.mimeType, rhs.mimeType)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PickedFileInfo")
    deepHashTransferApi(value: path, hasher: &hasher)
    deepHashTransferApi(value: name, hasher: &hasher)
    deepHashTransferApi(value: sizeBytes, hasher: &hasher)
    deepHashTransferApi(value: mimeType, hasher: &hasher)
  }
}

private class TransferApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PickedFileInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class TransferApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PickedFileInfo {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class TransferApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return TransferApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return TransferApiPigeonCodecWriter(data: data)
  }
}

class TransferApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = TransferApiPigeonCodec(readerWriter: TransferApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FileHostApi {
  /// Open the native file picker (supports multi-select).
  /// Returns a list of [PickedFileInfo] objects for each selected file.
  func pickFiles(completion: @escaping (Result<[PickedFileInfo], Error>) -> Void)
  /// Save a file from [tempPath] to the public Downloads folder via MediaStore
  /// (Android) or the app's Documents directory (iOS).
  /// Returns the final saved path / content URI.
  func saveToDownloads(tempPath: String, mimeType: String, fileName: String, completion: @escaping (Result<String, Error>) -> Void)
  /// Returns available storage space in bytes.
  func getFreeSpace(completion: @escaping (Result<Int64, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FileHostApiSetup {
  static var codec: FlutterStandardMessageCodec { TransferApiPigeonCodec.shared }
  /// Sets up an instance of `FileHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FileHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Open the native file picker (supports multi-select).
    /// Returns a list of [PickedFileInfo] objects for each selected file.
    let pickFilesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neoshare.FileHostApi.pickFiles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickFilesChannel.setMessageHandler { _, reply in
        api.pickFiles { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickFilesChannel.setMessageHandler(nil)
    }
    /// Save a file from [tempPath] to the public Downloads folder via MediaStore
    /// (Android) or the app's Documents directory (iOS).
    /// Returns the final saved path / content URI.
    let saveToDownloadsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neoshare.FileHostApi.saveToDownloads\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveToDownloadsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tempPathArg = args[0] as! String
        let mimeTypeArg = args[1] as! String
        let fileNameArg = args[2] as! String
        api.saveToDownloads(tempPath: tempPathArg, mimeType: mimeTypeArg, fileName: fileNameArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveToDownloadsChannel.setMessageHandler(nil)
    }
    /// Returns available storage space in bytes.
    let getFreeSpaceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neoshare.FileHostApi.getFreeSpace\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFreeSpaceChannel.setMessageHandler { _, reply in
        api.getFreeSpace { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getFreeSpaceChannel.setMessageHandler(nil)
    }
  }
}
/// Flutter → Android: control the TransferForegroundService.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TransferServiceHostApi {
  /// Start the foreground service for the given transfer.
  func startUploadService(transferId: String) throws
  /// Stop the foreground service (upload finished or cancelled).
  func stopUploadService() throws
  /// Update the persistent notification progress (0–100).
  func updateProgress(percent: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TransferServiceHostApiSetup {
  static var codec: FlutterStandardMessageCodec { TransferApiPigeonCodec.shared }
  /// Sets up an instance of `TransferServiceHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TransferServiceHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Start the foreground service for the given transfer.
    let startUploadServiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neoshare.TransferServiceHostApi.startUploadService\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startUploadServiceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let transferIdArg = args[0] as! String
        do {
          try api.startUploadService(transferId: transferIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startUploadServiceChannel.setMessageHandler(nil)
    }
    /// Stop the foreground service (upload finished or cancelled).
    let stopUploadServiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neoshare.TransferServiceHostApi.stopUploadService\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopUploadServiceChannel.setMessageHandler { _, reply in
        do {
          try api.stopUploadService()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopUploadServiceChannel.setMessageHandler(nil)
    }
    /// Update the persistent notification progress (0–100).
    let updateProgressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.neoshare.TransferServiceHostApi.updateProgress\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateProgressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let percentArg = args[0] as! Int64
        do {
          try api.updateProgress(percent: percentArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateProgressChannel.setMessageHandler(nil)
    }
  }
}
/// Android → Flutter: service lifecycle callbacks.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol TransferServiceFlutterApiProtocol {
  /// Called when the OS restarts the service after killing it under memory pressure.
  func onServiceRestarted(transferId transferIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class TransferServiceFlutterApi: TransferServiceFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: TransferApiPigeonCodec {
    return TransferApiPigeonCodec.shared
  }
  /// Called when the OS restarts the service after killing it under memory pressure.
  func onServiceRestarted(transferId transferIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.neoshare.TransferServiceFlutterApi.onServiceRestarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([transferIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
